[db4s]
server = "docker-dev.dbhub.io"
port = 5550
certificate = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/docker-dev.dbhub.io.cert.pem"
certificate_key = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/docker-dev.dbhub.io.key.pem"
ca_chain = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/ca-chain-docker.cert.pem"

[diskcache]
directory = "/home/dbhub/.dbhub/disk_cache"

[environment]
environment = "docker"
user_override = "your_username_here"

[event]
delay = 2
email_queue_processing_delay = 5
email_queue_dir = "/home/dbhub/.dbhub/email_queue"

[licence]
licence_dir = "/go/src/github.com/sqlitebrowser/dbhub.io/default_licences"

[memcache]
default_cache_time = 2592000
server = "localhost:11211"
view_count_flush_delay = 120

[minio]
server = "localhost:9000"
access_key = "minio"
secret = "minio123"
https = false

[pg]
database = "dbhub"
num_connections = 45
port = 5432
server = "/tmp"
ssl = false
username = "dbhub"

[sign]
cert_days_valid = 365
intermediate_cert = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/intermediate-docker.cert.pem"
intermediate_key = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/intermediate-docker.key.pem"

[web]
base_dir = "/go/src/github.com/sqlitebrowser/dbhub.io"
bind_address = ":8443"
server_name = "docker-dev.dbhub.io:8443"
certificate = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/docker-dev.dbhub.io.cert.pem"
certificate_key = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/docker-dev.dbhub.io.key.pem"
request_log = "/var/log/dbhub/request.log"
session_store_password = "example"

[api]
base_dir = "/go/src/github.com/sqlitebrowser/dbhub.io"
bind_address = ":8444"
server_name = "docker-dev.dbhub.io:8444"
certificate = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/docker-dev.dbhub.io.cert.pem"
certificate_key = "/go/src/github.com/sqlitebrowser/dbhub.io/docker/certs/docker-dev.dbhub.io.key.pem"
request_log = "/var/log/dbhub/api_request.log"
session_store_password = "example2"
website_name = "DBHub.io"
